### ISSUE TITLE
terrible bug report with horrible/no feedback

### ISSUE THREAD

**Issue by MEP239** [Mordarski-Networks/Mordarski-Networks-assets#42]
When you open the generate filter on windows 10 it crashes

**Comment by MEP239** [comment]
It still doesnt work, maybe its on my side. Idk

**Comment by smordarski** [comment]
> It still doesnt work, maybe its on my side. Idk

Hello @MEP239, sorry for responding late. Can you please post the errors when running the script? If you don't know how, I will tell you.

## Windows

If you are on Windows 10 and 11, do this:

1. Download [Git for Windows](https://github.com/git-for-windows/git/releases). Make sure to download the one that says Git-2.45.1-64-bit.exe.
2. Download [Python](https://www.python.org/downloads/).
3. In a terminal, do `git clone https://github.com/Mordarski-Networks/Mordarski-Networks-assets.git`.
4. Then change your directory to our repository by doing `cd Mordarski-Networks-assets\scripts`.
5. Run the Python script by doing `python generate_filter.py`.
6. Post the error by text or a screenshot. You can use this command to copy the errors to the clipboard `python generate_filter.py | clip`.

## Linux

If you are on Linux, do this:

1. For Debian/Ubuntu, do `sudo apt install git python3.12` to install Git and Python 3.12.
2. In a terminal, do `git clone https://github.com/Mordarski-Networks/Mordarski-Networks-assets.git`.
3. Then change your directory to our repository by doing `cd Mordarski-Networks-assets/scripts`.
4. Run the Python script by doing `python3.12 generate_filter.py`.
5. Post the error by text or a screenshot. You can use this command to copy the errors to the clipboard `python3.12 generate_filter.py | xclip -sel clipboard`.

**Comment by MEP239** [comment]
It was on my side :/ i didnt download it correctly. Thanks tho
